### 1. DEFINING WORKFLOW ###
### 2. CORE COMPONENTS ###
name: Java CICD with Maven # name [optional] is displayed on your repos action page

### 3. EVENTS / TRIGGERS ###
### 4. WORKFLOW EXECUTION ###
on: # on [required] - name of Github event that triggers the workflow
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs: # jobs [required] - one or more jobs, sequence of tasks (steps)
# steps can run commands, setup tasks OR run an action
    build:
    ### 5. RUNNERS ###
    runs-on: ubuntu-latest
    ### 6. ACTIONS ###
    steps:
        -   uses: actions/checkout@v4 
        -   name: Set up JDK 17
        -   uses: actions/setup-java@v4
        -   with: 
                java-version: "17"
                distribution: "temurin"
                cache: "maven"
        -   name: build with Maven
                # run - runs a command-line command
                run: mvn - B package pom.xml
        -   name: upload artifacts
            uses: actions/upload-artifacts@v4
            with:
                name: target-files
                path: target
